name: qlgl_project
description: A Rice seed manager project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter_screenutil: ^5.7.0
  animated_splash_screen: ^1.3.0
  lottie: ^2.3.2

  get: ^4.6.5
  http: ^0.13.5
  dio: ^5.1.2
  get_storage: ^2.1.1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  
  shared_preferences: ^2.0.18
  flutter_svg: ^1.1.6
  
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.4.0
  slide_digital_clock: ^1.0.3
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  full_screen_image: any
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.7+5
  
  
  
  
  
  

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
